%token EOF DOT COMMA SEMICOLON COLON PLUS MINUS STAR SLASH PERCENT AMPERSAND BAR CARET TILDE EXCLAM QUEST EQUALS LESSTHEN GREATTHEN LBRACKET RBRACKET LPAREN RPAREN LBRACE RBRACE GTE LTE EQU NEQ ASR SHL LOGICOR LOGICAND CATCH ELSE FALSE FOR IF THROW TRUE TRY VAR WHILE ID INT CHAR STRING ERR CONST ADD_EQ SUB_EQ DIV_EQ MOD_EQ MUL_EQ AND_EQ OR_EQ XOR_EQ SHL_EQ ASR_EQ
%%

program 		: EOF
				| stat program
				| semi_stat semi_list
				| compound_stat program
//				| function_def program
				;

semi_list		: EOF
				| ';' program
				;

// --------------------------------------------------------------------------
// Variables
// -------------------------------------------------------------------------- 

var_list 		: var var_list1
				;

var_list1 		: 
				| ',' var_list
				;

var				: ID { op_var_decl, op_push_tmp } var_init_opt
				;

var_init_opt    : { op_pop_tmp }
				| '=' exp { op_var_init }
				;

// --------------------------------------------------------------------------
// Update (assignment) operators
// -------------------------------------------------------------------------- 

assign_or_call1	: '=' exp { op_var_assign }
				| ADD_EQ { op_var_eval } additive_exp { op_add, op_var_assign }
				| SUB_EQ { op_var_eval } additive_exp { op_sub, op_var_assign }
				| DIV_EQ { op_var_eval } div_exp { op_div, op_var_assign }
				| MOD_EQ { op_var_eval } div_exp { op_mod, op_var_assign }
				| MUL_EQ { op_var_eval } mult_exp { op_mul, op_var_assign }
				| AND_EQ { op_var_eval } and_exp { op_and, op_var_assign }
				| OR_EQ  { op_var_eval } exp { op_or, op_var_assign }
				| XOR_EQ { op_var_eval } exp { op_xor, op_var_assign }
				| SHL_EQ { op_var_eval } shift_exp	{ op_shl, op_var_assign }
				| ASR_EQ { op_var_eval } shift_exp	{ op_asr, op_var_assign }
				| function_call { op_ret_discard }
				| '[' exp ']' { op_array_xlat } '.' attr_assign
				| '.'{ op_object_get } attr_assign
				;

attr_assign		: ID { op_push_tmp } attr_assign2
				;

attr_assign2    : '=' exp { op_attr_assign }
				| '[' exp ']' '=' exp { op_array_assign }
				| method_call { op_ret_discard }
				;

// --------------------------------------------------------------------------
// Constants
// -------------------------------------------------------------------------- 

const_list 		: const const_list1
				;

const_list1 	: 
				| ',' const_list
				;

const			: ID { op_const_decl, op_push_tmp } '=' const_exp { op_const_init }
				;

const_exp		: exp
				;

// --------------------------------------------------------------------------
// Method calls
// -------------------------------------------------------------------------- 

method_call		: { op_method_lookup } '(' arg_list_opt ')' { op_call } 
				;

// --------------------------------------------------------------------------
// Function calls
// -------------------------------------------------------------------------- 

function_call	: { op_function_lookup } '(' arg_list_opt ')' { op_call } 
				;

arg_list_opt	: 
				| arg_list 
				;

arg_list		: exp { op_arg } arg_list1 
				;

arg_list1		: 
				| ',' arg_list 
				;

// --------------------------------------------------------------------------
// For loop comma separated list of expressions
// -------------------------------------------------------------------------- 

exp_lst_opt		: 
				| exp_lst
				;

exp_lst			: ID { op_push_tmp } assign_or_call1 exp_lst1
				;
				
exp_lst1		: 
				| ',' exp_lst
				;

// --------------------------------------------------------------------------
// Expressions
// -------------------------------------------------------------------------- 

exp 			: and_exp or_exp
				;

or_exp			: 
				| '|' exp { op_or }
				| LOGICOR exp { op_logic_or }
				| '^' exp { op_xor }
				;

and_exp			: relational_exp and_exp1
				;

and_exp1		: 
				| '&' and_exp { op_and }
				| LOGICAND and_exp { op_logic_and }
				;

relational_exp	: shift_exp	relational_exp1
				;

relational_exp1	:
				| '<' relational_exp { op_lt }
				| '>' relational_exp { op_gt }
				| EQU relational_exp { op_equ }
				| NEQ relational_exp { op_neq }
				| GTE relational_exp { op_gte }
				| LTE relational_exp { op_lte }
				;

shift_exp		: additive_exp shift_exp1
				;

shift_exp1		: 
				| SHL shift_exp	{ op_shl }
				| ASR shift_exp	{ op_asr }
				;

additive_exp 	: div_exp additive_exp1
				;

additive_exp1 	: 
				| '+' additive_exp { op_add }
				| '-' additive_exp { op_sub }
				;


div_exp			: mult_exp div_exp1		
				;

div_exp1		: 
				| '/' div_exp { op_div }
				| '%' div_exp { op_mod }
				;

mult_exp		: unary_exp mult_exp1		
				;

mult_exp1		: 
				| '*' mult_exp { op_mul }
				;

unary_exp		: primary_exp
				| '~' unary_exp { op_inv }
				| '-' unary_exp { op_minus }
				| NOT unary_exp { op_not }
				;

primary_exp		: '(' exp ')'
				| INT { op_push_int }
				| CHAR { op_push_int }
				| STRING { op_push_string }
				| "true" { op_push_true }
				| "false" { op_push_false }
				| id_eval
				;

id_eval 		: ID { op_push_tmp } id_eval1
				;

id_eval1		: { op_var_eval }
				| function_call { op_call_ret }
				| '[' exp ']' { op_array_xlat } '.' attr_eval
				| '.' { op_object_get } attr_eval		
				;

attr_eval		: ID { op_push_tmp } attr_eval1
				;


attr_eval1		: { op_attr_eval }
				| method_call { op_call_ret }
				| '[' exp ']' { op_array_eval }
				;

// --------------------------------------------------------------------------
// Statements
// -------------------------------------------------------------------------- 

compound_stat	: '{' { op_blk_open } stat_list '}' { op_blk_close } 
				;

stat_list		:
				| stat stat_list
				| semi_stat ';' stat_list
				;

loop_comp_stat	: '{' { op_blk_open } loop_stat_list '}' { op_blk_close } 
				;

loop_stat_list	:
				| stat loop_stat_list
				| semi_stat ';' loop_stat_list
				| "break" ';' {op_loop_break}
				| "continue" ';' {op_loop_continue}
				;


stat			: "for" { op_blk_open } '(' exp_lst_opt ';' { op_for_init } exp { op_for_cond } ';' exp_lst_opt { op_for_after } ')' loop_comp_stat	{ op_for_end, op_blk_close }
				| "while" { op_while_begin } condition { op_while_cond } loop_comp_stat	{ op_while_end }
				| "do" { op_do_while_begin } loop_comp_stat	"while" condition { op_do_while_cond,  op_do_while_end } ';'
				| "if" condition { op_if_cond } compound_stat else_opt { op_patch_ref }

				| "try" { op_try_begin } compound_stat catch_opt 
				;

condition		: '(' exp ')'
				;

semi_stat		: "throw" exp { op_throw }
				| "var" var_list
				| "const" const_list
				| "return" retval_opt
				| ID { op_push_tmp } assign_or_call1
				;

else_opt		: 
				| "else" { op_if_else } compound_stat
				;

catch_opt		: { op_try_end }
				| "catch" { op_catch, op_blk_open } '(' ID { op_var_decl, op_push_tmp, op_var_init } ')' '{' stat_list '}' { op_blk_close, op_patch_ref }
				;

retval_opt      : { op_return }
				| exp { op_retval }
				;



// --------------------------------------------------------------------------
// Function definitions
// -------------------------------------------------------------------------- 

function_def 	: "function" ID { op_fun_def, op_blk_open } '(' arg_lst_opt ')' '{'  stat_list '}' { op_return, op_patch_ref } 
				;

arg_lst_opt		: 
				| arg_lst
				;

arg_lst			: ID { op_arg_decl } arg_opt
				;
				
arg_opt 		: 
				| ',' arg_lst
				;

